# Generated by Django 3.0.6 on 2020-05-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawelblog', '0003_post_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
    ]
